# Generated by Django 4.1.2 on 2022-10-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price_per_month', models.FloatField()),
                ('price', models.FloatField()),
                ('duration', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
