# Generated by Django 4.1.2 on 2022-10-24 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_course_image_alter_post_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 24, 18, 4, 40, 115988)),
        ),
    ]
