# Generated by Django 4.1.2 on 2022-10-26 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_post_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_per_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 17, 6, 12, 273666)),
        ),
    ]
