# Generated by Django 4.1.2 on 2022-10-27 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_course_price_alter_course_price_per_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 19, 52, 59, 579910)),
        ),
    ]
