# Generated by Django 4.1.2 on 2022-10-25 10:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0003_alter_learnuser_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 10, 48, 50, 895452)),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2022, 10, 25, 10, 48, 50, 897524))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_app.category')),
            ],
        ),
    ]
