# Generated by Django 4.1.2 on 2022-10-25 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0004_category_alter_subscription_purchase_time_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 11, 25, 48, 494083, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
