# Generated by Django 4.1.2 on 2022-10-25 11:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0005_alter_subscription_purchase_time_delete_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 11, 25, 58, 71184, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2022, 10, 25, 11, 25, 58, 75552, tzinfo=datetime.timezone.utc))),
                ('video', models.FileField(upload_to='videos/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_app.category')),
            ],
        ),
    ]
