# Generated by Django 4.1.2 on 2022-10-26 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0006_alter_subscription_purchase_time_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 17, 6, 12, 277440, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 17, 6, 12, 275223, tzinfo=datetime.timezone.utc)),
        ),
    ]
