# Generated by Django 4.1.2 on 2022-10-27 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0007_alter_content_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 19, 52, 59, 584772, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 19, 52, 59, 582665, tzinfo=datetime.timezone.utc)),
        ),
    ]
