# Generated by Django 4.1.2 on 2022-10-27 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0008_category_image_alter_content_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='preview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 20, 44, 12, 586862, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 20, 44, 12, 582436, tzinfo=datetime.timezone.utc)),
        ),
    ]
