# Generated by Django 4.1.2 on 2022-10-27 22:14

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn_app', '0009_category_preview_alter_content_create_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='purchase_time',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='duration_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='title',
            field=models.CharField(default='fix', max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 22, 14, 31, 864345, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_time', models.DateTimeField(default=datetime.datetime(2022, 10, 27, 22, 14, 31, 861893, tzinfo=datetime.timezone.utc))),
                ('cost', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('subscribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_app.subscription')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('expire_date', models.DateTimeField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
