# Generated by Django 4.1.2 on 2022-10-27 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0015_alter_content_create_date_alter_permission_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='duration_days',
            new_name='duration_month',
        ),
        migrations.AlterField(
            model_name='content',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 22, 36, 56, 555748, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 22, 36, 56, 554136, tzinfo=datetime.timezone.utc)),
        ),
    ]
