# Generated by Django 4.1.2 on 2022-10-28 08:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0016_rename_duration_days_subscription_duration_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnuser',
            name='active_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learn_app.subscription'),
        ),
        migrations.AddField(
            model_name='learnuser',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnuser',
            name='is_subscriber',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='content',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 8, 28, 42, 232180, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='purchase_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 8, 28, 42, 230596, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
